FROM nginx:stable-alpine

RUN apk add --no-cache \
		ca-certificates

ENV PATH /usr/local/go/bin:$PATH

ENV GOLANG_VERSION 1.17rc1
ENV IPFS_URL https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz

RUN wget -O ipfs.tgz "$IPFS_URL"; \
	tar -C /usr/local -xzf ipfs.tgz; \
	rm ipfs.tgz; 

# install fuse
RUN apk update -U \
    && apk add --no-cache --virtual .build-deps git \
    && apk add fuse; \
    mkdir /ipfs; \
    mkdir /ipns;

COPY ./src/ /usr/share/nginx/html/
ENTRYPOINT [ "ipfs daemon --mount" ]