# run with --privileged 
FROM nginx:stable

ENV PATH /usr/local/go/bin:$PATH

ENV IPFS_URL https://dist.ipfs.io/go-ipfs/v0.9.0/go-ipfs_v0.9.0_linux-amd64.tar.gz

RUN curl "$IPFS_URL" > ipfs.tgz; \
        tar -C /usr/local -xzf ipfs.tgz; \
        rm ipfs.tgz; \
        bash /usr/local/go-ipfs/install.sh; \
        ipfs --version;

# install fuse
RUN apt-get update  \
    && apt-get -y install fuse; \
    mkdir /ipfs; \
    mkdir /ipns;

COPY ./src/ /usr/share/nginx/html/
CMD [ "/usr/local/ipfs daemon --mount &; ", "nginx", "-g", "daemon off;"]